[package]
name = "astro_modloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unreal_modloader = { version = "0.1.0", path = "../unreal_modloader" }
