[package]
name = "unreal_asset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
enum_dispatch = "0.3.8"
num_enum = "0.5.6"
lazy_static = "1.4.0"
ordered-float = "2.10.0"
bitflags = "1.3.2"
