[package]
name = "unreal_asset"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
enum_dispatch = "0.3.8"
num_enum = "0.5.7"
lazy_static = "1.4.0"
ordered-float = "3.0.0"
bitflags = "1.3.2"
