[package]
name = "unreal_asset"
version.workspace = true
authors.workspace = true
description.workspace = true
edition = "2021"

[dependencies]
bitflags = "1.3.2"
bitvec = "1.0.1"
byteorder.workspace = true
enum_dispatch = "0.3.8"
lazy_static.workspace = true
num_enum.workspace = true
ordered-float = "3.2.0"

[features]
oodle = []