[workspace]

members = [
    "unreal_pak", "unreal_pak_cli",
    "unreal_asset",
    "unreal_modloader", "unreal_modintegrator",
    "astro_modloader"
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1


[patch.crates-io]
steamy-vdf = { git = "https://github.com/icewind1991/steamy" }