[package]
name = "upak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.7"
byteorder = "1.4.3"
flate2 = { version = "1.0.22", features = ["zlib"], default-features = false }
