[package]
name = "unreal_pak"
version = "0.1.0"
edition = "2021"

[dependencies]
num_enum = "0.5.7"
byteorder = "1.4.3"
flate2 = { version = "1.0.24", features = ["zlib"], default-features = false }
sha-1 = "0.10.0"
