[package]
name = "unreal_pak"
version.workspace = true
authors.workspace = true
description.workspace = true
edition = "2021"

[dependencies]
byteorder.workspace = true
flate2 = { version = "1.0.24", features = ["zlib"], default-features = false }
num_enum.workspace = true
sha-1 = "0.10.0"
