[package]
name = "unreal_modloader"
version = "0.1.0"
edition = "2021"

[dependencies]
unreal_modintegrator = { version = "0.1.0", path = "../unreal_modintegrator" }

directories = "4.0.1"
eframe = "0.18.0"
egui_extras = "0.18.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
log = "0.4.17"
steamlocate = "1.0.1"
reqwest = { version = "0.11.11", features = ["blocking"] }
regex = "1.6.0"
lazy_static = "1.4.0"
winreg = "0.10.1"
open = "3.0.2"
parking_lot = "0.12.1"
