[package]
name = "unreal_modloader"
version = "0.1.0"
edition = "2021"

[dependencies]
unreal_modintegrator = { version = "0.1.0", path = "../unreal_modintegrator" }
unreal_pak = { version = "0.1.0", path = "../unreal_pak" }
directories = "4.0.1"
#eframe = "0.17.0"
eframe = { git = "https://github.com/emilk/egui" }
#egui_extras = "0.17.0"
egui_extras = { git = "https://github.com/emilk/egui" }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
steamlocate = "1.0.1"
reqwest = { version = "0.11.10", features = ["blocking"] }
