[package]
name = "unreal_modloader"
version = "0.1.0"
edition = "2021"

[dependencies]
unreal_modintegrator = { version = "0.1.0", path = "../unreal_modintegrator" }
unreal_pak = { version = "0.1.0", path = "../unreal_pak" }
directories = "4.0.1"
eframe = "0.18.0"
egui_extras = "0.18.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
log = "0.4.16"
steamlocate = "1.0.1"
reqwest = { version = "0.11.10", features = ["blocking"] }
regex = "1.5.5"
lazy_static = "1.4.0"
