[package]
name = "unreal_modloader"
version = "0.1.0"
edition = "2021"

[dependencies]
unreal_modintegrator = { version = "0.1.0", path = "../unreal_modintegrator" }
eframe = "0.17.0"
directories = "4.0.1"
steamlocate = "1.0.1"
