[package]
name = "unreal_modloader"
version = "0.1.0"
edition = "2021"

[dependencies]
unreal_modintegrator = { version = "0.1.0", path = "../unreal_modintegrator" }
directories = "4.0.1"
eframe = "0.17.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
steamlocate = "1.0.1"
